version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: mysql2
    restart: always
    ports:
      - 3333:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=testdb
      - TZ=Asia/Seoul
    command: --lower_case_table_names=2
    volumes:
      - ./db/mysql2/data:/var/lib/mysql
      - ./db/mysql2/init:/docker-entrypoint-initdb.d